dist: focal

language: python

python:
  - "3.8"
  - "3.9"
  - "3.10"

install:
  - python setup.py install

script:
  - bash tests/test_a.sh
  - bash tests/test_N0.sh
  - bash tests/test_N3.sh
  - bash tests/test_identical_files.sh
  - python -m unittest discover tests
